package code

// 不同状态的响应码
const (
	SUCCESS = "SUCCESS"

	INVALID_REQUEST = "INVALID_REQUEST"
	MISSING_PARAMS  = "MISSING_PARAMS"
	WRONG_PARAMS    = "WRONG_PARAMS"

	INTERNAL_ERROR = "INTERNAL_ERROR"

	NOT_FOUND      = "NOT_FOUND"
	ALREADY_EXISTS = "ALREADY_EXISTS"
)
